[workspace]
members = ["programs/noctura-shield"]

[provider]
cluster = "devnet"
wallet = "/Users/banel/config/solana/id.json"

[programs.devnet]
noctura_shield = "3KN2qrmEtPyk9WGu9jJSzLerxU8AUXAy8Dp6bqw5APDz"

[programs.testnet]
noctura_shield = "3KN2qrmEtPyk9WGu9jJSzLerxU8AUXAy8Dp6bqw5APDz"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.29.0"
