services:
  - type: web
    name: noctura-relayer
    runtime: docker
    region: oregon
    plan: starter
    rootDir: zk/prover-service
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8787
      - key: SOLANA_RPC_URL
        value: https://api.devnet.solana.com
      - key: HELIUS_API_KEY
        value: 5d57d00d-0ea2-4fe1-8d81-bc8b4aed3f18
      - key: USE_RAPIDSNARK
        value: "true"
